// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AegisPreflightVerdict } from "../AegisPreflightVerdict";
import type { AegisSecretRiskCategory } from "../AegisSecretRiskCategory";

export type AegisPreflightDecisionNotification = { threadId: string, call_id: string, turn_id: string, tool_name: string, verdict: AegisPreflightVerdict, risk_category?: AegisSecretRiskCategory, reason: string, required_evidence_ids: Array<string>, command?: Array<string>, paths: Array<string>, };
