// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AegisSecretRiskCategory = "sensitive_command" | "cloud_mutation" | "repository_mutation" | "credential_access" | "destructive_action" | "sandbox_escape" | "other";
