// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MethodIssueProvider } from "./MethodIssueProvider";

export type MethodLinkedIssue = { provider: MethodIssueProvider, repository: string, number: bigint, title?: string, url?: string, };
