// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MethodSandboxPolicySummary } from "./MethodSandboxPolicySummary";

export type MethodSandboxPosture = { mode: string, permission_profile: string, enforcement: string, network: string, policy?: MethodSandboxPolicySummary, };
