// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type MethodResumeValidityReason = "missing_persisted_repository" | "missing_current_repository" | "repository_mismatch" | "missing_persisted_branch" | "missing_current_branch" | "branch_changed" | "missing_persisted_commit" | "missing_current_commit" | "commit_changed" | "missing_persisted_issue" | "missing_current_issue" | "issue_mismatch" | "missing_persisted_schema_version" | "missing_current_schema_version" | "schema_version_mismatch" | "missing_persisted_sandbox_posture" | "missing_current_sandbox_posture" | "sandbox_posture_changed";
