// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { MethodSandboxPolicyStatus } from "./MethodSandboxPolicyStatus";

export type MethodSandboxPolicySummary = { status: MethodSandboxPolicyStatus, allowed_modes: Array<string>, source?: string, diagnostic?: string, };
